const Vulnerability = require('../../models/Vulnerabilities');
const Company = require('../../models/Company');
const Users = require('../../models/Users');
const Report = require('../../models/Reports');
const CompanyOffer = require('../../models/CompanyOffers');
const Platform = require('../../models/Platform');
const generateOffer = require('./generateOffer');
const generateDictatorOffer = require('./generateDicOffer');
const { EmbedBuilder } = require('discord.js');
const testVulnData = require('../../data/test-data.json');

// Intervals (ms)
const GEN_MIN_MS = Number(process.env.CONT_GEN_MIN_MS || 5 * 60 * 1000); // 5 minutes
const GEN_MAX_MS = Number(process.env.CONT_GEN_MAX_MS || 10 * 60 * 1000); // 10 minutes
const EXPIRE_AFTER_MS = Number(process.env.CONT_EXPIRE_AFTER_MS || 30 * 60 * 1000); // 30 minutes
const SWEEP_MS = Number(process.env.CONT_SWEEP_MS || 60 * 1000); // sweep every 1 minute
const CONT_TICK_MS = Number(process.env.CONT_TICK_MS || 5 * 60 * 1000); // 5-minute checker

let genTimeout = null;
let sweepInterval = null;
let tickInterval = null;
let clientRef = null;

function randBetween(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

async function resolveAnnouncementsChannel(client) {
    try {
        const guilds = client.guilds.cache;
        const guild = guilds.first() || (await client.guilds.fetch().then(col => col.first()).catch(() => null));
        if (!guild) return null;
        await guild.channels.fetch();
        let channel = guild.channels.cache.find(ch => ch.type === 0 && ch.name.toLowerCase() === 'announcements');
        if (!channel) channel = guild.channels.cache.find(ch => ch.type === 0 && ch.name.toLowerCase().includes('general'));
        return channel || null;
    } catch (_) {
        return null;
    }
}

async function announceExpired(vuln) {
    if (!clientRef) return;
    const channel = await resolveAnnouncementsChannel(clientRef);
    if (!channel) return;

    const embed = new EmbedBuilder()
        .setTitle('🧯 Company Patched a Vulnerability')
        .setDescription(`The company has discovered and patched vulnerability ${vuln.vuln_identifier}.`)
        .addFields(
            { name: 'Severity', value: vuln.severity || 'LOW', inline: true },
        )
        .setTimestamp(new Date());
    channel.send({ embeds: [embed] }).catch(() => {});
}

function pickAnswer(val) {
    if (val == null) return undefined;
    if (typeof val === 'string') return val;
    if (typeof val === 'object' && typeof val.answer === 'string') return val.answer;
    return undefined;
}

async function generateOneVulnerability() {
    const companies = await Company.find({});
    const users = await Users.find({});
    if (!companies.length || !users.length || !testVulnData?.length) return null;

    const company = companies[randBetween(0, companies.length - 1)];
    const data = testVulnData[randBetween(0, testVulnData.length - 1)];

    const visibilityGlobal = Math.random() < 0.6;
    const allowedUsers = visibilityGlobal ? [] : users
        .sort(() => 0.5 - Math.random())
        .slice(0, randBetween(1, Math.min(3, users.length)))
        .map(u => u._id);

    const vulnIdentifier = `${data.type || 'XSS'}-${company.name?.toUpperCase()?.replace(/[^A-Z0-9]/g, '').slice(0, 6) || 'COMP'}-${Date.now().toString().slice(-5)}`;

    const expiration = new Date(Date.now() + EXPIRE_AFTER_MS);

    const vulnDoc = await Vulnerability.create({
        company_id: company._id,
        round_id: null,
        vuln_identifier: vulnIdentifier,
        volun_type: data.type || 'Other',
        severity: data.severity || 'LOW',
        name: data.name || 'Generated Vulnerability',
        description: data.description || 'This vulnerability was generated by the continuous mode.',
        networkAccess: { answer: pickAnswer(data.networkAccess) },
        arbitraryCodeExecution: { answer: pickAnswer(data.arbitraryCodeExecution) },
        userInteraction: { answer: pickAnswer(data.userInteraction) },
        automatable: { answer: pickAnswer(data.automatable) },
        confidentialityImpact: { answer: pickAnswer(data.confidentialityImpact) },
        integrityImpact: { answer: pickAnswer(data.integrityImpact) },
        availabilityImpact: { answer: pickAnswer(data.availabilityImpact) },
        privilegesRequired: { answer: pickAnswer(data.privilegesRequired) },
        recoveryPotential: { answer: pickAnswer(data.recoveryPotential) },
        isReported: false,
        isResolved: false,
        expiration_date: expiration,
        visibility: {
            isGlobal: visibilityGlobal,
            allowedUsers
        }
    });

    return vulnDoc;
}

async function scheduleNextGeneration() {
    const delay = randBetween(GEN_MIN_MS, GEN_MAX_MS);
    genTimeout = setTimeout(async () => {
        try { await generateOneVulnerability(); } catch (e) { console.error('generateOneVulnerability error:', e); }
        finally { scheduleNextGeneration(); }
    }, delay);
}

async function sweepExpirations() {
    const now = new Date();
    const toExpire = await Vulnerability.find({ isResolved: false, expiration_date: { $lte: now } });
    for (const v of toExpire) {
        v.isResolved = true;
        v.is_resolved_date = now;
        try {
            await v.save();
            await announceExpired(v);
        } catch (e) {
            console.error('expire save error:', e);
        }
    }
}

// ===== 5-MINUTE CHECKER (Reports/Offers/POC) =====
const VISIBILITY_FIELDS = [
    'networkAccess',
    'arbitraryCodeExecution',
    'userInteraction',
    'automatable',
    'confidentialityImpact',
    'integrityImpact',
    'availabilityImpact',
    'privilegesRequired',
    'recoveryPotential',
];

function countVisibleFieldsForUser(vuln, userId) {
    if (!vuln) return 0;
    const uid = userId?.toString();
    let count = 0;
    for (const f of VISIBILITY_FIELDS) {
        const node = vuln[f];
        const list = node?.visibleTo || [];
        if (list.some(x => x?.toString() === uid)) count += 1;
    }
    return count;
}

async function evaluateAutoOffers(client) {
    // Collect all non-POC-only reports that are attached to a vulnerability
    const reports = await Report.find({ is_poc_only: { $ne: true }, vulnerability_id: { $ne: null } });
    if (!reports.length) return;

    const byVuln = new Map();
    for (const r of reports) {
        const key = r.vulnerability_id?.toString();
        if (!key) continue;
        if (!byVuln.has(key)) byVuln.set(key, []);
        byVuln.get(key).push(r);
    }

    const now = new Date();
    for (const [vulnId, vulnReports] of byVuln.entries()) {
        const vuln = await Vulnerability.findById(vulnId);
        if (!vuln) continue;

        // Skip resolved or expired vulns
        if (vuln.isResolved) continue;
        if (vuln.expiration_date && vuln.expiration_date <= now) continue;

        // If there is already a pending offer for any of these reports, skip
        const pendingForVuln = await CompanyOffer.findOne({ report_id: { $in: vulnReports.map(r => r._id) }, status: 'pending' });
        if (pendingForVuln) continue;

        const perUser = new Map();
        for (const r of vulnReports) {
            const uid = r.user_id?.toString();
            if (!uid) continue;
            const visible = countVisibleFieldsForUser(vuln, r.user_id);
            const entry = perUser.get(uid) || { visibleCount: visible, earliestReport: r, earliestAt: r.submitted_at || r.createdAt, count: 0 };
            if (visible > entry.visibleCount) entry.visibleCount = visible;
            const ts = r.submitted_at || r.createdAt;
            if (!entry.earliestAt || (ts && ts < entry.earliestAt)) {
                entry.earliestAt = ts;
                entry.earliestReport = r;
            }
            entry.count = (entry.count || 0) + 1;
            perUser.set(uid, entry);
        }

        if (!perUser.size) continue;

        const totalFields = VISIBILITY_FIELDS.length;
        const fullUsers = Array.from(perUser.entries())
            .filter(([, v]) => v.visibleCount >= totalFields)
            .sort((a, b) => (a[1].earliestAt || now) - (b[1].earliestAt || now));

        let chosenReport = null;
        if (fullUsers.length) {
            chosenReport = fullUsers[0][1].earliestReport;
            await Vulnerability.updateOne({ _id: vuln._id }, { $set: { offer_wait_started_at: null, last_offer_report_id: chosenReport._id } });
        } else {
            if (!vuln.offer_wait_started_at) {
                await Vulnerability.updateOne({ _id: vuln._id }, { $set: { offer_wait_started_at: now } });
                continue;
            }
            const waitedMs = now.getTime() - new Date(vuln.offer_wait_started_at).getTime();
            if (waitedMs < CONT_TICK_MS) continue;

            // Fallback after waiting: user who submitted the most, tie-break by earliest submission
            const ranked = Array.from(perUser.entries())
                .sort((a, b) => {
                    if ((b[1].count || 0) !== (a[1].count || 0)) return (b[1].count || 0) - (a[1].count || 0);
                    return (a[1].earliestAt || now) - (b[1].earliestAt || now);
                });
            chosenReport = ranked[0][1].earliestReport;
            await Vulnerability.updateOne({ _id: vuln._id }, { $set: { offer_wait_started_at: null, last_offer_report_id: chosenReport._id } });
        }

        if (!chosenReport) continue;

        const existing = await CompanyOffer.findOne({ report_id: chosenReport._id, status: 'pending' });
        if (existing) continue;

        try {
            const user = await Users.findById(chosenReport.user_id);
            if (!user?.discord_id) continue;
            const duser = await client.users.fetch(user.discord_id);

            // Decide offer type based on platform
            let useDictator = false;
            try {
                if (chosenReport.platform_id) {
                    const platform = await Platform.findById(chosenReport.platform_id);
                    if (platform) {
                        const nameHas = (platform.name || '').toLowerCase().includes('dictator');
                        const variantsHas = Array.isArray(platform.variants) && platform.variants.some(v => String(v).toLowerCase().includes('dictator'));
                        useDictator = nameHas || variantsHas;
                    }
                }
            } catch (_) { /* no-op */ }

            if (useDictator) {
                await generateDictatorOffer(client, chosenReport, duser);
            } else {
                await generateOffer(client, chosenReport, duser);
            }

            // Notify and reward non-selected reporters for this vulnerability
            const losers = vulnReports.filter(r => String(r._id) !== String(chosenReport._id));
            for (const loser of losers) {
                try {
                    const lUser = await Users.findById(loser.user_id);
                    if (lUser?.discord_id) {
                        const lDiscord = await client.users.fetch(lUser.discord_id).catch(() => null);
                        if (lDiscord) {
                            await lDiscord.send({
                                content: `Thanks for your report on ${vuln.vuln_identifier || 'the recent vulnerability'}. Another researcher received the main offer. You have been awarded $100 and a reputation bonus for your contribution.`
                            }).catch(() => {});
                        }
                    }
                    // Credit $100 and reputation bonus if not already granted
                    const bonusRep = 10;
                    const updates = {
                        $inc: { money_earned: 100, repuation_earned: bonusRep }
                    };
                    await Users.updateOne({ _id: loser.user_id }, updates);
                    await Report.updateOne({ _id: loser._id }, {
                        $inc: { offered_amount: 100, reputation_bonus: bonusRep },
                        $set: { status: 'closed' }
                    });
                } catch (e) {
                    console.error('Failed to reward/notify non-selected reporter:', e);
                }
            }
        } catch (e) {
            console.error('Failed to send auto-offer:', e);
        }
    }
}

async function evaluateTick(client) {
    try {
        await evaluateAutoOffers(client);
    } catch (e) {
        console.error('Continuous tick error:', e);
    }
}

async function initialize(client) {
    clientRef = client;
    if (!genTimeout) await scheduleNextGeneration();
    if (!sweepInterval) sweepInterval = setInterval(sweepExpirations, SWEEP_MS);
    // On start, sweep immediately to normalize state
    await sweepExpirations();
    // Start 5-minute checker
    if (!tickInterval) tickInterval = setInterval(() => {
        evaluateTick(clientRef).catch(e => console.error('CONT tick error:', e));
    }, CONT_TICK_MS);
}

function cleanupTimers() {
    if (genTimeout) { clearTimeout(genTimeout); genTimeout = null; }
    if (sweepInterval) { clearInterval(sweepInterval); sweepInterval = null; }
    if (tickInterval) { clearInterval(tickInterval); tickInterval = null; }
}

module.exports = {
    initialize,
    cleanupTimers,
};
